update_check = true
auto_sync = true
sync_frequency = "5m"
sync_address = "https://atuin.cuasar.cc"

style = "full"
inline_height = 20

show_preview = true
show_numeric_shortcuts = false
show_help = false
show_tabs = false
enter_accept = false

[keys]
scroll_exits = false

[sync]
records = true

[theme]
name = "custom-theme"
